#kita gunakan web server nginx sebagai base image
FROM nginx:alpine

#kita copy seluruh file aset statis ke dalam folder /usr/share/nginx/html
COPY . /usr/share/nginx/html

#kita expose port 80
EXPOSE 80